language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.3.1
install:
  - pip install Django==$DJANGO
  - pip install south django-sekizai python-openid djangorestframework markdown
# command to run tests
script: python test_manage.py test character_manager game_manager